const {chromium}=require('C:/Users/wang/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),assert=require('assert');const out=path.resolve(__dirname,'../acceptance');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const report={browser:await browser.version(),sizes:[],checks:[],errors:[]};try{
 for(const [width,height]of [[390,844],[844,390],[768,1024],[1024,768],[1366,768],[1920,1080]]){const context=await browser.newContext({viewport:{width,height}}),p=await context.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8773/');await p.locator('[data-year="2010"]').click();await p.waitForFunction(()=>document.querySelectorAll('#sourceContent .flow-page').length===14);await p.waitForTimeout(700);for(const mode of ['word','sentence']){const el=p.locator('#quickbar [data-mode="'+mode+'"]');await el.click();const b=await el.boundingBox();assert(b&&b.x>=0&&b.y>=0&&b.x+b.width<=width&&b.y+b.height<=height,mode+' not visible');}assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'horizontal overflow');await p.locator('[data-view="text"]').click();if(width<=1050)await p.locator('[data-mobile="source"]').click();await p.locator('#source-2010-3 [data-flow-word]').first().click();assert((await p.locator('#detailContent').innerText()).includes('本地点读'));await p.screenshot({path:path.join(out,'chrome-'+width+'x'+height+'.png')});report.sizes.push({width,height,modeButtonsVisible:true,horizontalOverflow:false,errors});assert.deepEqual(errors,[]);await context.close()}
 const context=await browser.newContext({viewport:{width:1366,height:768}}),p=await context.newPage();let requests=[];p.on('request',r=>requests.push(r.url()));p.on('pageerror',e=>report.errors.push(e.message));await p.goto('http://127.0.0.1:8773');await p.locator('[data-year="2010"]').click();await p.locator('[data-view="text"]').click();await p.locator('#quickbar [data-mode="word"]').click();requests=[];for(let i=2;i<22;i++){const b=p.locator('#source-2010-3 [data-flow-word="'+i+'"]');await b.click();const style=await b.evaluate(e=>({color:getComputedStyle(e).color,bg:getComputedStyle(e).backgroundColor}));assert.notEqual(style.bg,'rgb(0, 0, 0)')}await p.locator('#quickbar [data-mode="sentence"]').click();for(let i=30;i<40;i++)await p.locator('#source-2010-3 [data-flow-word="'+i+'"] ').click();const aiRequests=requests.filter(x=>/api\.openai\.com|\/api\/(ai|chat|analysis|responses)/.test(x));assert.equal(aiRequests.length,0);report.checks.push({name:'20 word + 10 sentence clicks',aiRequests,network:[...requests]});
 await p.locator('[data-view="paper"]').click();const hit=p.locator('#source-2010-3 [data-flow-hit="5"]');await hit.click();const paint=await hit.evaluate(e=>({fill:getComputedStyle(e).fill,stroke:getComputedStyle(e).stroke}));assert(!['rgb(0, 0, 0)','black'].includes(paint.fill));await hit.focus();await p.keyboard.press('Enter');report.checks.push({name:'SVG pointer and keyboard',paint});
 await p.locator('#pageSelect').selectOption('2010-4');await p.locator('[data-question="22"]').click();await p.locator('[data-answer="C"]').click();await p.getByRole('button',{name:'确认当前答案',exact:true}).click();assert((await p.locator('#answerEditor').innerText()).includes('错题'));await p.locator('#answerNote').fill('测试：定位与范围');await p.locator('#askAI').click();await p.locator('#chatInput').fill('为什么不能选 C');await p.locator('#chatSend').click();assert((await p.locator('#handoffText').inputValue()).includes('2010'));await p.locator('#codexReply').fill('测试保存答复，不代表真实 AI 分析。');await p.locator('#saveCodexReply').click();await p.reload();await p.locator('[data-year="2010"]').click();await p.locator('#pageSelect').selectOption('2010-4');await p.locator('[data-question="22"]').click();assert.equal(await p.locator('#answerNote').inputValue(),'测试：定位与范围');await p.locator('#askAI').click();assert((await p.locator('#chatLog').innerText()).includes('测试保存答复'));report.checks.push({name:'confirmed answer, note, per-question pasted conversation persistence',passed:true});await p.locator('#closeChat').click();
 await p.locator('#pageSelect').selectOption('2010-3');await p.locator('[data-view="text"]').click();await p.locator('#source-2010-3 [data-flow-word="12"]').click();await p.getByRole('button',{name:'模糊',exact:true}).click();await p.reload();await p.locator('[data-year="2010"]').click();await p.locator('#vocabCards').click();assert((await p.locator('#dialogBody').innerText()).includes('模糊'));await p.locator('#closeDialog').click();report.checks.push({name:'vocabulary persistence',passed:true});
 await p.evaluate(()=>{document.querySelector('#sourceContent').scrollTop=1e5});await p.waitForTimeout(700);assert(await p.locator('#sourceContent .flow-page').count()===14);assert(await p.locator('#sourceContent img').count()<8);report.checks.push({name:'source virtualization',decodedImages:await p.locator('#sourceContent img').count()});
 await p.locator('#backHome').click();await p.locator('[data-year="2026"]').click();await p.waitForFunction(()=>document.querySelector('#detailContent').textContent.includes('解析待补充'));report.checks.push({name:'missing reference honest state',passed:true});
 await p.evaluate(()=>document.documentElement.style.zoom='2');const buttons=await p.locator('#quickbar button').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height}}));assert(buttons.every(b=>b.x>=0&&b.x+b.w<=1366));report.checks.push({name:'200% CSS zoom quickbar',passed:true});await context.close();assert.deepEqual(report.errors,[]);
 }finally{fs.writeFileSync(path.join(out,'browser-report.json'),JSON.stringify(report,null,2));await browser.close()}console.log(JSON.stringify(report,null,2))})().catch(e=>{console.error(e);process.exit(1)});
