import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..'),ctx={window:{}};
vm.createContext(ctx);
for(const name of ['data.js','study-store.js'])vm.runInContext(fs.readFileSync(path.join(root,'dist',name),'utf8'),ctx);
const d=ctx.window.STUDY_DATA,store=ctx.StudyStore,q=d.questions.find(q=>q.id===22),s=store.fresh();
assert.equal(store.grade(s,q),'pending');
assert.equal(store.stats(s,d.questions).wrong,0);
s.confirmed[q.id]=true;
assert.equal(store.grade(s,q),'wrong');
const original=store.chosen(s,q);
store.recordRetry(s,q,q.answer,'2026-09-11T00:00:00.000Z');
assert.equal(store.chosen(s,q),original,'Retry must preserve original answer');
assert.equal(store.grade(s,q),'wrong','Retry must not rewrite original grade');
assert.equal(s.attempts.length,1);
s.notes[q.id]='只看到了 fashion，漏掉了后文对收藏家的解释。';
s.tags[q.id]=['定位错误'];s.mastered[q.id]=true;
assert.equal(store.stats(s,d.questions).mastered,1);
const map=new Map(),memory={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)};
store.save(memory,s);const loaded=store.load(memory,d);
assert.equal(loaded.warning,null);assert.equal(loaded.state.notes[q.id],s.notes[q.id]);
assert.equal(loaded.state.attempts[0].answer,q.answer);
assert.equal(store.chosen(loaded.state,q),original);
for(const bad of [{year:2022},{year:2010,answers:{22:'E'}},{year:2010,notes:{22:'x'.repeat(2001)}},{year:2010,confirmed:{22:'yes'}},JSON.parse('{"year":2010,"answers":{"__proto__":{"polluted":true}}}'),{year:2010,attempts:[{question:22,answer:'A',at:'invalid'}]}])assert.throws(()=>store.validate(bad,d));
assert.equal({}.polluted,undefined);
map.clear();map.set('study2010.answers',JSON.stringify({22:'B'}));map.set('study2010.confirmed',JSON.stringify({22:true}));
assert.equal(store.load(memory,d).state.answers[22],'B','Migrate v1');
map.set(store.KEY,'{broken');assert(store.load(memory,d).warning);assert.equal(map.get(store.KEY),'{broken','Do not delete damaged records');
const empty=store.validate({year:2010,answers:{22:null},confirmed:{22:true}},d);assert.equal(store.grade(empty,q),'empty');
const clamped=store.validate({year:2010,last:{passage:2,page:10,question:40,zoom:99,view:'evil',scrolls:{'text:3':40,'__proto__':50}}},d);
assert.equal(clamped.last.page,5);assert.equal(clamped.last.zoom,2);assert.equal(clamped.last.view,'text');
console.log('PASS: pending grades, retry isolation, mastery, backup roundtrip, v1 migration, corrupt storage recovery, validation and location constraints.');
